# Generated by Django 2.1 on 2022-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20220313_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=30)),
                ('movies', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
