# Generated by Django 2.1 on 2022-03-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caster',
            name='movies',
        ),
        migrations.DeleteModel(
            name='Caster',
        ),
    ]
